# Generated by Django 4.1.3 on 2022-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_steg', '0004_postfile_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='name',
            field=models.FileField(upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='type_file_id',
            field=models.CharField(choices=[('', 'Selectionner une option'), ('1', 'document(.txt, .pdf, .docx)'), ('2', 'audio(.wav, .mp3)'), ('3', 'videos(.mp4, .avi)')], default='Selectionner une option', max_length=70),
        ),
    ]
